[package]
name = "ass-stroke"
version.workspace = true
edition = "2021"

[dependencies]
smallvec = "1.10.0"
range-map = "0.2.0"
random_color = "0.6.1"
rand = { version = "0.8.5", features = ["small_rng"] }
num-traits = "0.2.15"
